# -*- coding: utf-8 -*-
"""nlp_traning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZmQvMZ87sGSv68q3MbLfxDaYeM-LQKj
"""

from joblib import dump
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
import os

# Read data from CSV files in the same folder
x_train = pd.read_csv("x_train.csv", index_col=0)
x_test = pd.read_csv("x_test.csv", index_col=0)
y_train = pd.read_csv("y_train.csv", index_col=0)
y_test = pd.read_csv("y_test.csv", index_col=0)

# Count Vectorization and TF-IDF Transformation
count_vect = CountVectorizer(stop_words='english')
transformer = TfidfTransformer(norm='l2', sublinear_tf=True)

x_train_counts = count_vect.fit_transform(x_train['text'])
x_train_tfidf = transformer.fit_transform(x_train_counts)

x_test_counts = count_vect.transform(x_test['text'])
x_test_tfidf = transformer.transform(x_test_counts)

# Random Forest Model
model = RandomForestClassifier(n_estimators=200)
model.fit(x_train_tfidf, y_train)

# Save the Random Forest Model in the same folder
MODEL_NAME = 'random_forest_model.joblib'
dump(model, MODEL_NAME)

